name: Build

on:
  push:
    branches: [main, master]
    tags: ['v*']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Brand Kit Package
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Clean previous builds
        run: npm run clean

      - name: Build package
        run: npm run build

      - name: Verify build output
        run: |
          if [ ! -d "dist" ]; then
            echo "Build failed: dist directory not found"
            exit 1
          fi
          echo "Build successful: dist directory created"
          ls -la dist/

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: brand-kit-dist
          path: dist/
          retention-days: 30

      - name: Upload package files
        uses: actions/upload-artifact@v4
        with:
          name: brand-kit-package
          path: |
            package.json
            README.md
            LICENSE.md
            CONTRIBUTING.md
          retention-days: 30
